version: '3'
services:
  db:
    image: mongo:5.0
    ports: 
      - "27017:27017"
    
   
  webapp:
    build: ./web-app
    ports:
      - "4000:4000"
    depends_on:
      - db

  mlclient:
    build: ./ml-client
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - "8.8.8.8"
    depends_on:
      - db
  