name: Deploy to DO
on:
  push:
    branches:
      - digitalocean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Install DigitalOcean Controller
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Authenticate with DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 500
      - name: Build and Push to DigitalOcean Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: |
            registry.digitalocean.com/styletransfer/api:1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ml-client
          file: ./ml-client/Dockerfile
          push: true
          tags: registry.digitalocean.com/styletransfer/api:2     

  deploy-api-1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Droplets already have docker, doctl + auth, and curl installed
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_API1_HOST }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            doctl registry login --expiry-seconds 180
            docker pull registry.digitalocean.com/styletransfer/api:1

            docker run -d \
              --restart always \
              -p 0.0.0.0:4000:4000 \
              --name api \
              registry.digitalocean.com/styletransfer/api:1

  deploy-api-2:
    needs: deploy-api-1 # rolling deploy
    runs-on: ubuntu-latest
    steps:
      # Droplets already have docker, doctl + auth, and curl installed
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_API2_HOST }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            doctl registry login --expiry-seconds 180
            docker pull registry.digitalocean.com/styletransfer/api:2
            docker run -d \
              --restart always \
              -p 0.0.0.0:3000:3000 \
              --name api \
              registry.digitalocean.com/styletransfer/api:latest