name: CD

on:
  push:
    branches:
      - 'digitalocean'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to digital ocean
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: dop_v1_1d4c82767e37395df8cad0629c85275119dcf09d4b9d82660bf654f2a500d657
          password: dop_v1_1d4c82767e37395df8cad0629c85275119dcf09d4b9d82660bf654f2a500d657
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: registry.digitalocean.com/project5-team5:1
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./ml-client
          file: ./ml-client/Dockerfile
          push: true
          tags: registry.digitalocean.com/project5-team5:2