name: CI & CD

on:
  push:
    branches:
      'digitalocean'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        run: docker login registry.digitalocean.com --username=dop_v1_f6a5ee4caeeac47e5326e4cebdaeb41cbafff6a219ee6db5930a45b02b943c3f
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: zackdan/project5-team5-deploy:1 , registry.digitalocean.com/project5-team5:1
      -
        name: Build and push
        uses: docker/build-push-action@v3
        run: docker login registry.digitalocean.com --username=dop_v1_f6a5ee4caeeac47e5326e4cebdaeb41cbafff6a219ee6db5930a45b02b943c3f
        with:
          context: ./ml-client
          file: ./ml-client/Dockerfile
          push: true
          tags: zackdan/project5-team5-deploy:2 , registry.digitalocean.com/project5-team5:2
